[package]
name = "ycat"
version = "0.2.0"
edition = "2021"
description = "Concatenate multiple YAML files into a single YAML stream and write it to stdout"
license = "GPL-3.0-only"

[features]
gentest = []

[dependencies]
anyhow = "1.0.93"
