name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: cargo build --verbose --release

      - name: Test
        run: cargo test --verbose --release

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/ycat
          generate_release_notes: true
